spring:
  application:
    name: CookMates
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/recipe_sharing
    username: hoanghuy
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
cloudinary:
  cloud-name: dp0tcvlag
  api-key: 929913749946788
  api-secret: _bgXach9hiqwxu9JfU8mPTPhYFo